# The least square method

In [79]:
''' 
The least-squares method is a statistical method used to find the line of best fit of the form of an equation such as y = mx + b to the given data. 
The curve of the equation is called the regression line.
'''

' \nThe least-squares method is a statistical method used to find the line of best fit of the form of an equation such as y = mx + b to the given data. \nThe curve of the equation is called the regression line.\n'

In [80]:
import numpy as np

# Example data
X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([10, 20, 30])





# Calculate gammas using the formula: γ = (X^T · X)^-1 · X^T · y
XTX_inv = np.linalg.inv(X.T.dot(X))
XTy = X.T.dot(y)
gamma = XTX_inv.dot(XTy)

print("Coefficient vector gamma:")
print(gamma)



Coefficient vector gamma:
[-4.08562073e-14  5.00000000e+00]


# Multicolinearity

In [81]:
""" 
https://towardsdatascience.com/targeting-multicollinearity-with-python-3bd3b4088d0b 
https://www.youtube.com/watch?v=Z0-oV87e7LU&t=273s&ab_channel=Kckurzy


    - exceeds 0.8 or -0.8

removing:
    - převod na postupné diference - shift by difference
    - drop one feature with lower correlation to y
    - keep it there - small influence on results 
    - dummy - after performing differences (write 0 for negative and write 1 for positive)
"""

' \nhttps://towardsdatascience.com/targeting-multicollinearity-with-python-3bd3b4088d0b \nhttps://www.youtube.com/watch?v=Z0-oV87e7LU&t=273s&ab_channel=Kckurzy\n\n\n    - exceeds 0.8 or -0.8\n\nremoving:\n    - převod na postupné diference - shift by difference\n    - drop one feature with lower correlation to y\n    - keep it there - small influence on results \n    - dummy - after performing differences (write 0 for negative and write 1 for positive)\n'

**Pearson matrix of correlation**

In [82]:
import numpy as np

# Sample data matrix
data = np.array([[0.1, 2, 3], [0.4, 5, 6], [7, 8, 9]])

# Compute Pearson correlation coefficients
corr_matrix = np.corrcoef(data, rowvar=False)

print("Matrix of Pearson correlation coefficients:")
print(corr_matrix)

Matrix of Pearson correlation coefficients:
[[1.         0.88461538 0.88461538]
 [0.88461538 1.         1.        ]
 [0.88461538 1.         1.        ]]


**Multiply a matrix by a vector**

In [ ]:
import numpy as np

# Define a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Define a vector
vector = np.array([1, 2, 3])

# Perform matrix-vector multiplication
result = np.dot(matrix, vector)

print("Matrix:")
print(matrix)
print("\nVector:")
print(vector)
print("\nResult of matrix-vector multiplication:")
print(result)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Vector:
[1 2 3]

Result of matrix-vector multiplication:
[14 32 50]


# Recursive filter

In [ ]:
import statsmodels.tsa.api as tsa
import pandas as pd


In [ ]:
''' 
y(t) = y(t-1)*2 + x(t)
'''

In [ ]:
x = [10, 20, 30, 40, 50]
new = tsa.filters.recursive_filter(x, 2)
new

array([ 10.,  40., 110., 260., 570.])

In [ ]:
def filter(x, beta):
    result = tsa.filters.recursive_filter(x, beta)
    return result

In [ ]:
df = pd.DataFrame({'value' : [10, 20, 30]})

In [ ]:
df['recursive'] = filter(df['value'],beta=2)
df

value    new
0     10   10.0
1     20   40.0
2     30  110.0

**Add second function**

In [ ]:
# second function
def second(x, alfa):
    return x ** alfa

In [ ]:
df['second'] = second(filter(df['value'],beta=2), alfa=2)
df

value    new   second
0     10   10.0    100.0
1     20   40.0   1600.0
2     30  110.0  12100.0

**Loop with combinations**

In [87]:
from itertools import product

x = [1, 2, 3]
y = [10, 20, 30]


for first_item, second_item in product(x, y):
    print(first_item, second_item)

1 10
1 20
1 30
2 10
2 20
2 30
3 10
3 20
3 30


# Scaling

In [11]:
import pandas as pd
import numpy as np

In [138]:
df = pd.DataFrame({'x1': [10, 40, 80],
                  'x2':[20, 20, 30],
                  'x3':[10, 30, 20],
                  'unit_vector':[1, 1, 1], 
                  'y-usd': [51, 111, 351]})

X = df[['x1', 'x2', 'x3', 'unit_vector']].to_numpy()
y = df[['y-usd']].to_numpy()

# Calculate gammas using the formula: γ = (X^T · X)^-1 · X^T · y
XTX_inv = np.linalg.inv(X.T.dot(X))
XTy = X.T.dot(y)
gamma = XTX_inv.dot(XTy)

print("Coefficient vector gamma:")
print(gamma)

Coefficient vector gamma:
[[ 12.5]
 [ -2. ]
 [ -6. ]
 [128. ]]


In [137]:
df = pd.DataFrame({'x1': [10, 40, 80],
                  'x2':[20, 20, 30],
                  'x3':[100, 300, 200],
                  'unit_vector':[1, 1, 1], 
                  'y-usd': [51, 111, 351]})

X = df[['x1', 'x2', 'x3', 'unit_vector']].to_numpy()
y = df[['y-usd']].to_numpy()

# Calculate gammas using the formula: γ = (X^T · X)^-1 · X^T · y
XTX_inv = np.linalg.inv(X.T.dot(X))
XTy = X.T.dot(y)
gamma = XTX_inv.dot(XTy)

print("Coefficient vector gamma:")
print(gamma)

Coefficient vector gamma:
[[   2.75   ]
 [  17.     ]
 [  -0.15625]
 [-128.     ]]


**Without unit-vector**

In [121]:
df = pd.DataFrame({'x1': [10, 40, 80],
                  'x2':[20, 20, 30],
                  'x3':[100, 300, 200],
                  'unit_vector':[1, 1, 1], 
                  'y-usd': [50, 110, 350]})

X = df[['x1', 'x2', 'x3']].to_numpy()
y = df[['y-usd']].to_numpy()

# Calculate gammas using the formula: γ = (X^T · X)^-1 · X^T · y
XTX_inv = np.linalg.inv(X.T.dot(X))
XTy = X.T.dot(y)
gamma = XTX_inv.dot(XTy)

print("Coefficient vector gamma:")
print(gamma)

Coefficient vector gamma:
[[ 4.52173913]
 [ 2.13043478]
 [-0.37826087]]


In [122]:
df = pd.DataFrame({'x1': [10, 40, 80],
                  'x2':[20, 20, 30],
                  'x3':[10, 30, 20],
                  'unit_vector':[1, 1, 1], 
                  'y-usd': [50, 110, 350]})

X = df[['x1', 'x2', 'x3']].to_numpy()
y = df[['y-usd']].to_numpy()

# Calculate gammas using the formula: γ = (X^T · X)^-1 · X^T · y
XTX_inv = np.linalg.inv(X.T.dot(X))
XTy = X.T.dot(y)
gamma = XTX_inv.dot(XTy)

print("Coefficient vector gamma:")
print(gamma)

Coefficient vector gamma:
[[ 4.52173913]
 [ 2.13043478]
 [-3.7826087 ]]
